# Generated by Django 5.2.2 on 2025-06-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('cert', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('single_stick_capacity', models.IntegerField(blank=True, null=True)),
                ('double_stick_capacity', models.IntegerField(blank=True, null=True)),
                ('ddr_type', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='PCIE_16x_slot_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='VRAM',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='tdp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='FAN_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='M2_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='PCIE_16x_slot_type',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='PCIE_16x_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='PCIE_1x_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='PCIE_8x_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='SATA_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='VRM_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='WATERPUMP_slot',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='audio_chipset',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='chipset',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ethernet_max_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ram_ddr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ram_max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ram_max_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ram_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='L3cache',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='all_core_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='ddr4_compatible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='ddr5_compatible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='efficient_cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='igpu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='oc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='oc_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='performance_cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='real_all_core_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='single_core_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='tdp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='threads',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='socket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
