# Generated by Django 5.2.2 on 2025-06-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_psu_ram_graphicscard_pcie_16x_slot_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form_factor', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('glass_panel', models.BooleanField(blank=True, null=True)),
                ('max_gpu_size', models.IntegerField(blank=True, null=True)),
                ('max_cpu_cooler_size', models.IntegerField(blank=True, null=True)),
                ('slot_2_5_inch', models.IntegerField(blank=True, null=True)),
                ('slot_3_5_inch', models.IntegerField(blank=True, null=True)),
                ('fan_slot_1', models.CharField(blank=True, max_length=50, null=True)),
                ('fan_slot_2', models.CharField(blank=True, max_length=50, null=True)),
                ('fan_slot_3', models.CharField(blank=True, max_length=50, null=True)),
                ('fan_slot_4', models.CharField(blank=True, max_length=50, null=True)),
                ('fan_slot_5', models.CharField(blank=True, max_length=50, null=True)),
                ('fan_slot_6', models.CharField(blank=True, max_length=50, null=True)),
                ('fan_slot_7', models.CharField(blank=True, max_length=50, null=True)),
                ('rgb_hub', models.BooleanField(blank=True, null=True)),
                ('fan_hub', models.BooleanField(blank=True, null=True)),
                ('PSU_placement', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPU_cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tdp', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('can_add_fan', models.BooleanField(blank=True, null=True)),
                ('decibels', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disc_type', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('slot_type', models.CharField(blank=True, max_length=50, null=True)),
                ('slot_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('rgb', models.BooleanField(blank=True, null=True)),
                ('CFM', models.FloatField(blank=True, null=True)),
                ('decibels', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thermal_Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conductivity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='motherboard',
            name='fan_headers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='minimum_VRM_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='VRAM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
