# Generated by Django 5.2.2 on 2025-06-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_graphicscard_tdp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicscard',
            name='tdp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
