# Generated by Django 5.2.2 on 2025-06-12 04:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_graphicscard_tdp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraphicsCard',
            new_name='gpu',
        ),
        migrations.RenameField(
            model_name='chassis',
            old_name='slot_2_5_inch',
            new_name='all_disc_slots',
        ),
        migrations.RenameField(
            model_name='chassis',
            old_name='slot_3_5_inch',
            new_name='all_fan_slots',
        ),
        migrations.RenameField(
            model_name='processor',
            old_name='oc',
            new_name='oc_possible',
        ),
        migrations.RemoveField(
            model_name='disc',
            name='slot_size',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='fan_headers',
        ),
        migrations.AddField(
            model_name='chassis',
            name='max_AIO_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpu_cooler',
            name='AIO_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpu_cooler',
            name='chassis_fan_slots_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpu_cooler',
            name='fan_headers_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpu_cooler',
            name='sockets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cpu_cooler',
            name='type_of_cooler',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='oc_possible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
