# Generated by Django 5.2.2 on 2025-06-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_rename_graphicscard_gpu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Processor',
            new_name='cpu',
        ),
    ]
