# Generated by Django 5.2.2 on 2025-06-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_pcbuild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='all_core_speed',
            new_name='all_core_turbo',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='real_all_core_speed',
            new_name='single_core_turbo',
        ),
    ]
