# Generated by Django 5.2.2 on 2025-06-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_rename_all_core_speed_cpu_all_core_turbo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='max_ddr4_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='max_ddr5_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
