# Generated by Django 5.2.2 on 2025-06-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_cpu_max_ddr4_speed_cpu_max_ddr5_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='tdp_oc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
