# Generated by Django 5.2.2 on 2025-06-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_cpu_average_max_oc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='cpu',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='tdp_oc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
