# Generated by Django 5.2.2 on 2025-06-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_rename_name_cpu_full_name_rename_name_gpu_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='L3cache',
            new_name='aacache',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='minimum_VRM_quality',
            new_name='minimumaa_vrm_quality',
        ),
    ]
