# Generated by Django 5.2.2 on 2025-06-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_rename_l3cache_cpu_aacache_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='aacache',
            new_name='l3cache',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='minimumaa_vrm_quality',
            new_name='minimum_vrm_quality',
        ),
    ]
