# Generated by Django 5.2.2 on 2025-06-19 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_rename_aacache_cpu_l3cache_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chassis',
            old_name='max_AIO_size',
            new_name='max_aio_size',
        ),
        migrations.RenameField(
            model_name='chassis',
            old_name='PSU_placement',
            new_name='psu_placement',
        ),
        migrations.RenameField(
            model_name='cpu_cooler',
            old_name='AIO_size',
            new_name='aio_size',
        ),
        migrations.RenameField(
            model_name='fan',
            old_name='CFM',
            new_name='cfm',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='PCIE_16x_slot_type',
            new_name='pcie_16x_slot_type',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='VRAM',
            new_name='vram',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='FAN_slots',
            new_name='fan_slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='M2_slots',
            new_name='m2_slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='PCIE_16x_slot_type',
            new_name='pcie_16x_slot_type',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='PCIE_16x_slots',
            new_name='pcie_16x_slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='PCIE_1x_slots',
            new_name='pcie_1x_slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='PCIE_8x_slots',
            new_name='pcie_8x_slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='SATA_slots',
            new_name='sata_slots',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='VRM_quality',
            new_name='vrm_quality',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='WATERPUMP_slot',
            new_name='waterpump_slot',
        ),
    ]
