# Generated by Django 5.2.2 on 2025-06-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_rename_max_aio_size_chassis_max_aio_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='vram',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
