# Generated by Django 5.2.2 on 2025-06-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0017_alter_gpu_vram'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
